export const NOTIFICATION_SERVICE = Symbol('NOTIFICATION_SERVICE');
export const NOTIFICATION_MODULE_CONFIG = Symbol('NOTIFICATION_MODULE_CONFIG');
export const IS_NOTIFICATION_ENABLED_DECORATOR_KEY = 'isNotificationEnabled';
