services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000' # API endpoint
      - '9001:9001' # Console (web UI)
    volumes:
      # Map the Windows "contentora-images" folder on your Desktop to /data in the container.
      - '${USERPROFILE}\OneDrive\Desktop\contentora-images:/data'
    environment:
      # Set your access keys
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: us-east-1
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
  # nest-starter-api:
  #   build:
  #     dockerfile: docker/development/Dockerfile
  #     context: .
  #   container_name: nest-starter-api-dev-con
  #   image: nest-starter-api:dev
  #   restart: always
  #   ports:
  #     - '8000:8000'
  #   env_file:
  #     - ./.env.development
  #   volumes:
  #     - .:/workspace
  #     - /workspace/node_modules
