services:
  contentora-api:
    build:
      dockerfile: docker/production/Dockerfile
      context: .
    image: contentora-api:prod
    container_name: contentora-api-prod-con
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./.env.production
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
