/**
 * Environments in which the application could be running
 */
export enum Environment {
  DEV = 'development',
  PROD = 'production',
  TEST = 'test',
}

/**
 * Configuration(Environment variables) keys
 */
export enum Config {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  API_PREFIX = 'API_PREFIX',
  API_DEFAULT_VERSION = 'API_DEFAULT_VERSION',
  DEBUG_MODE = 'DEBUG_MODE',
  GRACEFUL_SHUTDOWN_TIMEOUT = 'GRACEFUL_SHUTDOWN_TIMEOUT',
  ADMIN_USER_EMAIL = 'ADMIN_USER_EMAIL',
  ADMIN_USER_PASSWORD = 'ADMIN_USER_PASSWORD',
  SYSTEM_USER_EMAIL = 'SYSTEM_USER_EMAIL',
  SYSTEM_USER_PASSWORD = 'SYSTEM_USER_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_URL = 'DATABASE_URL',
  DATABASE_SSL = 'DATABASE_SSL',
  DATABASE_SSL_REJECT_UNAUTHORIZED = 'DATABASE_SSL_REJECT_UNAUTHORIZED',
  DATABASE_POOL_MAX_SIZE = 'DATABASE_POOL_MAX_SIZE',
  DATABASE_POOL_MIN_SIZE = 'DATABASE_POOL_MIN_SIZE',
  DATABASE_IDLE_TIMEOUT = 'DATABASE_IDLE_TIMEOUT',
  DATABASE_CONNECTION_TIMEOUT = 'DATABASE_CONNECTION_TIMEOUT',
  DATABASE_MAX_RETRIES = 'DATABASE_MAX_RETRIES',
  DATABASE_RETRY_DELAY = 'DATABASE_RETRY_DELAY',
  DATABASE_MAX_RETRY_DELAY = 'DATABASE_MAX_RETRY_DELAY',
  CACHE_HOST = 'CACHE_HOST',
  CACHE_PORT = 'CACHE_PORT',
  CACHE_PASSWORD = 'CACHE_PASSWORD',
  ELASTICSEARCH_NODE = 'ELASTICSEARCH_NODE',
  ELASTICSEARCH_USERNAME = 'ELASTICSEARCH_USERNAME',
  ELASTICSEARCH_PASSWORD = 'ELASTICSEARCH_PASSWORD',
  ELASTICSEARCH_SSL_VERIFY = 'ELASTICSEARCH_SSL_VERIFY',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_REGION = 'AWS_S3_REGION',
  AWS_S3_ENDPOINT = 'AWS_S3_ENDPOINT',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  UPLOAD_FILE_URL_EXPIRATION = 'UPLOAD_FILE_URL_EXPIRATION',
  FILE_TABLE_LOCK_TTL = 'FILE_TABLE_LOCK_TTL',
  UNUSED_FILE_RETENTION_DAYS = 'UNUSED_FILE_RETENTION_DAYS',
  CSRF_SECRET = 'CSRF_SECRET',
  CSRF_EXPIRATION_TIME = 'CSRF_EXPIRATION_TIME',
  CSRF_COOKIE_NAME = 'CSRF_COOKIE_NAME',
  COOKIE_PARSER_SECRET = 'COOKIE_PARSER_SECRET',
  JWT_ACCESS_SECRET = 'JWT_SECRET',
  JWT_ACCESS_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME',
  JWT_ISSUER = 'JWT_ISSUER',
  JWT_AUDIENCE = 'JWT_AUDIENCE',
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  BEHIND_PROXY = 'BEHIND_PROXY',
  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLE_LIMIT = 'THROTTLE_LIMIT',
}

export enum RedisDB {
  API_CACHE = 0,
  ORM_CACHE = 1,
  REQ_THROTTLE = 2,
}

export enum Role {
  ADMIN = 'admin',
  SYSTEM = 'system',
  TEACHER = 'teacher',
  STUDENT = 'student',
}

export enum SortDirection {
  ASC = 'asc',
  DESC = 'desc',
}

export enum CursorPaginateDirection {
  NEXT = 'next',
  PREVIOUS = 'previous',
}

export enum Action {
  CREATE = 'Create',
  READ = 'Read',
  UPDATE = 'Update',
  DELETE = 'Delete',
}

export enum Resource {
  PERMISSION = 'Permission',
  PERMISSION_GROUP = 'Permission Group',
  USER = 'User',
  USER_PERMISSION = 'User Permission',
}
